### ISSUE TITLE
Pass in any attributes/arguments that existed in the original template

### ISSUE THREAD

**Issue by lifeart** [lifeart/els-component-extraction-addon#1]
## from:

`template.hbs`
```hbs
<div>{{this.msg}}</div>
```

## to:

`template.hbs`
```hbs
<HelloWorld @msg={{this.msg}} />
```
`components/hello-world.hbs`
```hbs
<div>{{@msg}}</div>
```

refs: https://github.com/ember-template-lint/ember-template-recast

**Comment by lifeart** [comment]
sample implementation - https://astexplorer.net/#/gist/43cfbcb18d878f83403fe5d9142ab302/fb00a7a231bb8c3335df7423dc6286621e04b365

---

cases to figure out how to handle:

```hbs
{{@foo}} {{this.foo}}
```
-> adds `scoped` prefix for `this.` cases with overlapped namespaces.
```hbs
<MyComponent @foo={{@foo}} @scopedFoo={{this.foo}} />
-----------------------------------------
{{@foo}} {{@scopedFoo}}
```

---

```hbs
{{this.foo.bar}} {{this.foo.bar.baz}}
```
-> instead of `@bar={{this.foo.bar}} @baz={{this.foo.baz}}` - `@foo={{this.foo}}`
```hbs
<MyComponent @foo={{this.foo}} />
-----------------------------------------
{{@foo.bar}} {{@foo.bar.baz}}
```

**Comment by lifeart** [comment]
one more example - https://astexplorer.net/#/gist/f035b50dd7222759fc70e128557fd668/729932462b61b99b710676532e3bb5cd05be1faa

cases to figure out how to handle:
---
```hbs
{{#let this.boo as |foo|}}
-----
{{@foo}} {{this.foo}} {{foo}}
-----
{{/let}}
```

we need to use `registry` to check, if helper exists or not, if not - use `localFoo`, else - skip path.
like hasHelperWith name, or check for `.` inside `{data: false, this:false}` paths.

**Comment by lifeart** [comment]
https://astexplorer.net/#/gist/f035b50dd7222759fc70e128557fd668/745aaf5dd71dcc9499b27e162b765906afaa080a

**Comment by Alonski** [comment]
You are on 🔥

**Comment by lifeart** [comment]
looks like https://astexplorer.net/#/gist/b9f00c20c05206519afbb291970f9955/3c4a2ef4926f09c33ca5f1624a247005b5ea7236 is in a good shape, @Alonski could you take it for implementation?

**Comment by Alonski** [comment]
I will try to find the time this week to try to start tackling this :)
